// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGgYX3TbC-VmFZkF7jpaZf1F19cxM2hg',
    appId: '1:646956730571:android:2681e4a2f1ea7f3d7b734e',
    messagingSenderId: '646956730571',
    projectId: 'college-bus-tracker-33e19',
    storageBucket: 'college-bus-tracker-33e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZFhLdyPF2XJI4WBjGnhZUSe4LQoZ7v4',
    appId: '1:646956730571:ios:5ef508cf7f7dc4ef7b734e',
    messagingSenderId: '646956730571',
    projectId: 'college-bus-tracker-33e19',
    storageBucket: 'college-bus-tracker-33e19.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnZFhLdyPF2XJI4WBjGnhZUSe4LQoZ7v4',
    appId: '1:646956730571:ios:5ef508cf7f7dc4ef7b734e',
    messagingSenderId: '646956730571',
    projectId: 'college-bus-tracker-33e19',
    storageBucket: 'college-bus-tracker-33e19.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_XHYrusOEGJJS1C1BISWL07d0ZARnGc',
    appId: '1:646956730571:web:4de2da578e5d1b807b734e',
    messagingSenderId: '646956730571',
    projectId: 'college-bus-tracker-33e19',
    authDomain: 'college-bus-tracker-33e19.firebaseapp.com',
    storageBucket: 'college-bus-tracker-33e19.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_XHYrusOEGJJS1C1BISWL07d0ZARnGc',
    appId: '1:646956730571:web:0983363416b3d47f7b734e',
    messagingSenderId: '646956730571',
    projectId: 'college-bus-tracker-33e19',
    authDomain: 'college-bus-tracker-33e19.firebaseapp.com',
    storageBucket: 'college-bus-tracker-33e19.firebasestorage.app',
  );

}